# Generated by Django 3.2.9 on 2021-11-26 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_practice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='input',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
    ]
