# Generated by Django 3.2.9 on 2021-11-26 13:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_practice_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='id',
            field=models.CharField(default=api.models.id_gen, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
