# Generated by Django 3.2.9 on 2021-11-26 13:32

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_practice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='input',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='practice',
            name='id',
            field=models.CharField(default=api.models.id_gen, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
