# Generated by Django 3.2.9 on 2021-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211126_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='input',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
