# Generated by Django 3.2.9 on 2021-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_practice_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='input',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
